### ISSUE TITLE
Title Logo

### ISSUE THREAD

**Issue by aimalamiri** [Jimmy-JS/laravel-report-generator#11]
How to add a logo in the PDF report generator?

**Comment by ArtyomBist** [comment]
vendor/jimmyjs/laravel-report-generator/src/views/general-pdf-template.blade.php change template for own solution

**Comment by aimalamiri** [comment]
Thank you

**Comment by Jimmy-JS** [comment]
I add ability publish views to resources/views/vendor/jimmyjs using `php artisan vendor:publish` on v1.0.19 e132402 . 

@aimalamiri You should prevent edit template on vendor folder since it will be flushed when you update the package

**Comment by bkinnari** [comment]
Hello Jimmy-Js, can you please explain the process required to display logo in the report?
I ran the command php artisan vendor:publish. How can I supply my logo to be displayed on report?

**Comment by franzuandrez** [comment]
@bkinnari  i would like to know that too

**Comment by Jonesku** [comment]
@Jimmy-JS  can you please explain the process required to display logo in the report?
I ran the command php artisan vendor:publish. How can I supply my logo to be displayed on report?

**Comment by saydfuad** [comment]
For anyone still looking for this, after running ` php artisan vendor:publish` go to views folder then vendor and edit `general-pdf-template.blade.php`  with code bellow:

```
  <p><img src="{{ public_path('logo.png') }}"  alt="Logo"></p>

			        {{ $headers['title'] }}
```
