### ISSUE TITLE
ERR_INVALID_RESPONSE excel download

### ISSUE THREAD

**Issue by garinalv** [Jimmy-JS/laravel-report-generator#12]
hello i have an issue downloading excel when theres alot of rows seleccted , but when theres not a lot of rows selected its download fine . 
i got this error on chrome ERR_INVALID_RESPONSE
but when i download it from my local it worked :(
any help ?

**Comment by Jimmy-JS** [comment]
@garinalv This can be a memory limit / timeout problem since rendering report will use bunch of memory (depends on how much records). Try increase **memory_limit** and ** max_execution_time** in php.ini

**Comment by winnerawan** [comment]
i've this issue,  change memory_limit and max_execution_time not help, @garinalv how do you resolve this ?
