### ISSUE TITLE
Undefined variable: showNumColumn

### ISSUE THREAD

**Issue by markuskoehler** [Jimmy-JS/laravel-report-generator#13]
Hey all,

this issue suddenly appeared today, last week all worked fine. Whenever I want to run the PdfReport or ExcelReport, I get the exception "`Undefined variable: showNumColumn`".

After that, I tried to use `PdfReport::showNumColumn(0)->of(...)` but that did not help as well... Any idea? I don't need the num column, so any hack to quickly resolve this issue would be appreciated... Seems like the blades for PDF/Excel don't recognize this variable, for whatever reason...

@bgarrison25 Any idea why this is going wrong? Thanks in advance!

**Comment by Jimmy-JS** [comment]
@markuskoehler I'm going to check it asap

**Comment by Jimmy-JS** [comment]
I have update the code on release 1.0.18. It should be no problem now. Thanks!
