### ISSUE TITLE
I'm try like this, but i can't get pdf report.

### ISSUE THREAD

**Issue by dilshan8kt** [Jimmy-JS/laravel-report-generator#14]
public function report(){
        $title = 'Registered User Report';

        $meta = [
            'Registered on To ',
            'Sort By'
        ];

        $queryBuilder = User::select(['emp_code', 'first_name', 'middle_name', 'last_name']);

        $columns = [
            'EMP Code' => 'emp_code',
            'First Name' => 'first_name',
            'Middle Name' => 'middle_name',
            'Last Name' => 'last_name'
        ];

        return PdfReport::of($title, $meta, $queryBuilder, $columns)
            ->limit(20)
            ->stream();
    }

![capture](https://user-images.githubusercontent.com/29746106/41276895-42db4f88-6e43-11e8-8ef4-8e69706dd147.PNG)

**Comment by Jimmy-JS** [comment]
You should give $meta properties an key value pair. Example:
$meta = ['Age' => '> 50', 'Gender' => 'Male'];

**Comment by winnerawan** [comment]
got this problem too, but on localhost on mac it's working fine, on windows i got 'this pdf document might not be displayed ...

**Comment by Jimmy-JS** [comment]
@winnerawan can you provide the source code as well?

**Comment by winnerawan** [comment]
@Jimmy-JS 
here my code, working fine on mac, blank on windows and shared hosting
or repository at [this commit](https://github.com/winnerawan/koperasi_mahasiswa/commit/8a0178d99c090024689130fedb0a492999ca432a)
```php

public function report_today()
{
        // Report title
        $title = 'Laporan Penjualan Hari Ini';
        $meta = [];
        $orders = Order::select(['customers.name', 'payments.name as pembayaran', 'orders.total_price','orders.created_at'])->join('customers', 'customers.id', '=', 'orders.customer_id')->join('payments', 'payments.id', '=', 'orders.payment_id')->whereDate('orders.created_at', '=', Carbon::today());
        $columns = [
            'Pembeli' => 'name',
            'Pembayaran' => 'pembayaran',
            'Total' =>  'total_price',
            'Tanggal' => 'created_at'
        ];

        return PdfReport::of($title, $meta, $orders, $columns)->stream();
    }
}
```

**Comment by danielalejandromatheus** [comment]
There's ambiguity in your query, I think that's the reason why the report doesn't come as expected.
`'Pembeli' => 'name',` should be `'Pembeli' => 'customers.name',`,
`'Total' =>  'total_price',` should be `'Total' =>  'orders.total_price'` and
`'Tanggal' => 'created_at',` should be ` 'Tanggal' => 'orders.created_at'`

Also, this is kinda out of topic, but you should consider using the Eloquent relationship builder in your model, as the code will come a shorter, and easier to read  😸

**Comment by winnerawan** [comment]
@hitostacha thanks you, i'm new in laravel framework even in php

**Comment by hitostacha** [comment]
@winnerawan did it work? If it did, close the issue
