### ISSUE TITLE
How to generate report for parent child relationship

### ISSUE THREAD

**Issue by bkinnari** [Jimmy-JS/laravel-report-generator#18]
Hello,

I have two tables:
1) Parent table - Having parentId, parentName, parentGender
2) Child table - Having childid, parentid, childname, child gender, childbirthdate

I want to generate report something like

Parent Name, Parent Gender
Child Name, Child Date of Birth, Child Gender

Now e.g. 
Parent table has 2 records:
1) Tom, Male
2) Jerry, Female

Child table has 3 records.
1) Parent Id - 1, Child Name - Bob, Child Gender - Male, DOB - 20thFeb2016
2) Parent Id - 1, Child Name - Tos, Child Gender - Female, DOB - 14Jan2014
3) Parent Id - 2, Child Name - Mary, Child Gender - Female, DOB - 17Sept2017

How to generate such report where single parent can have 2 child rows after that another parent has 1 child row etc.

Please advise.

**Comment by danielalejandromatheus** [comment]
Have you tried grouping by parents?

**Comment by Jimmy-JS** [comment]
@bkinnari you can use groupBy function as mentioned by @hitostacha

**Comment by bkinnari** [comment]
I tried group by however, it shows 1 line per parent hence 2 lines in report for Tom and jerry with 1 child details.

Please note I want to format something like:

2 lines for header.

e.g. refer attached image My report.png (I need 2 lines header and below that details for each parent).
![my report](https://user-images.githubusercontent.com/39190111/43732465-6d450a5e-99cf-11e8-8756-d362e9c3e11f.png)
Any help would be highly appreciated.

Note: I tried putting these child table columns in columns array however it all comes in single row. How to bring columns title also in 2 separate row?

**Comment by danielalejandromatheus** [comment]
You're bringing the related model with Eloquent's relationship builder, right? If you have your relationship built with eloquent, try printing the model as an object in your columns array (it's not properly formatted, obviously), something like this:
```
$columns= [
                'Children' => function($result){
                    return $result->children;
                },
            ];
```

**Comment by bkinnari** [comment]
I have tried your suggestion, what it does is it shows those child columns also in single row, that is in my above example "SRNo ParentName Gender SR No. ChildName"

I want it in two separate line.

Please help.

**Comment by danielalejandromatheus** [comment]
Huh, what if you generate the reports of the children instead, and group by the parents in the report? grouping by in the query groups all the children in only one row (it works if you want to count the children or something of the sorts)

**Comment by bkinnari** [comment]
This didnt help with the existing template.  Any other alternate wihtout modifying template blade file please?

**Comment by Jimmy-JS** [comment]
Sorry but this one is not currently supported :(
