### ISSUE TITLE
How to get a stream object for a ExcelReport object

### ISSUE THREAD

**Issue by Athuli7** [Jimmy-JS/laravel-report-generator#2]
Hi,

My Implementation is queueing the report generation in the background and then storing in s3. How can I get a stream buffer that Storage->put can use ?

**Comment by Jimmy-JS** [comment]
On v1.0.20 (8f20ef8) you can get LaravelExcelWriter object using the `make()` function on ExcelReport class. You can do all laravel excel by maatwebsite method from LaravelExcelWriter object. including get stream object.
