### ISSUE TITLE
Published view not working

### ISSUE THREAD

**Issue by danielalejandromatheus** [Jimmy-JS/laravel-report-generator#22]
I published a the PDF response view and customized it, but when I generate the report, it shows the default view, do I have to change anything after publishing the package?

**Comment by danielalejandromatheus** [comment]
Found the answer, turns out that this package's vendor:publish views folder should be named "report-generator-view" and not jimmyjs, I hope @Jimmy-JS  can change that when he has the time

**Comment by Jimmy-JS** [comment]
Oh yeah you're right. I already fix this on v1.0.21 (1801825). Thank you @hitostacha for pointing out.
