### ISSUE TITLE
Hiding the no column breaks the table width

### ISSUE THREAD

**Issue by danielalejandromatheus** [Jimmy-JS/laravel-report-generator#23]
When you cast `showNumColumn(false)` on your `PdfReport`, it breaks the table's total width, is there a way to fix this?

Example without No (I'm trying to use the ID of my report to replace it)
![image](https://user-images.githubusercontent.com/40004595/43964375-b964fbca-9c8a-11e8-8bc8-219847959035.png)

Example with No
![image](https://user-images.githubusercontent.com/40004595/43964465-e60a6c5a-9c8a-11e8-9e69-545854564c2a.png)

**Comment by Jimmy-JS** [comment]
This a bug and has been fixed on v1.0.23 (9a35773). Thanks for your information! 😄
