### ISSUE TITLE
CSV Report adds number column without header, causing wrong header order

### ISSUE THREAD

**Issue by kambadprashant** [Jimmy-JS/laravel-report-generator#24]
In CSV Report generation, no. column header is not being added but number is added in value, this causes wrong header order. Ex. 

my_column_1       my_column_2       my_column_3       my_column_4
auto_added_no    my_val_1               my_val_2              my_val_3               my_val_4

Is this expected behavior? 

Also we can't use showNumColumn in CSV to prevent this

**Comment by zlanich** [comment]
This is happening for me too: http://zsl.io/ase5k3

**Comment by Jimmy-JS** [comment]
@kambadprashant @zlanich This is a bug and has been fixed on v.1.0.22 (766002c). Thank you for your info! 😄

**Comment by zlanich** [comment]
Excellent, @Jimmy-JS, thank you!

**Comment by kambadprashant** [comment]
Thank You @Jimmy-JS
