### ISSUE TITLE
PDF Header Overwrite First Line on Multi Pages

### ISSUE THREAD

**Issue by unlockr-ca** [Jimmy-JS/laravel-report-generator#28]
Hi, I have a problem with the header overwriting the first line on Multi Pages.

![image](https://user-images.githubusercontent.com/26488450/44481600-41e6c680-a614-11e8-9f72-9a1a5d6c0fda.png)

**Comment by Jimmy-JS** [comment]
Are you using laravel snappy for generating pdf report? if so, you should install wkhtmltopdf with version 0.12.0 to make the styling work with this package. For installation guide please see docs (readme)

**Comment by ArtyomBist** [comment]
add in your  template   style 

                   `table thead {
				display: table-row-group;
			}
			thead { display: table-header-group }
			tfoot { display: table-row-group }
			tr { page-break-inside: avoid }

			table.table {
		    	font-size: 17px;
		    	border-collapse: collapse;
		      }`

**Comment by unlockr-ca** [comment]
Thanks @skortabeast !
It's working. If another person read this issue, please note that you can access the template style by running
`php artisan vendor:publish` and selecting `laravel-report:view-template, ` 
you will then be able to edit the template in `/resources/views/vendor/laravel-report-generator/general-pdf-template`

**Comment by Jimmy-JS** [comment]
@skortabeast thank you for solution. @unlockr I updated the view to include these class so you don't have to publish views in v.1.0.24
