### ISSUE TITLE
[Feature] Export Report as JSON

### ISSUE THREAD

**Issue by unlockr-ca** [Jimmy-JS/laravel-report-generator#29]
Hi, do you know any way to export the report as JSON?

I know I can use the get method on the collection but I would like to have the same parsing / header as the PDF document.

**Comment by Jimmy-JS** [comment]
@unlockr sorry, but I don't get what you mean. can you provide the json output for example?

**Comment by Jimmy-JS** [comment]
I will close this feature request since no following response. Please fell free to open this if you have more details
