### ISSUE TITLE
Access-Control-Allow-Origin: * is not pass when downloading a Excel or CSV file

### ISSUE THREAD

**Issue by unlockr-ca** [Jimmy-JS/laravel-report-generator#30]
Access-Control-Allow-Origin: * is not pass when creating a Excel or CSV file it is when you stream the PDF document.

**Comment by Jimmy-JS** [comment]
@unlockr Add this code might work. 
```
$this->make($filename)->export('xls', [
    'header-key' => 'header-value',
    'other-header-key' => 'other-header-value'
]);
```
You can view this issue on maatwebsite: [https://github.com/Maatwebsite/Laravel-Excel/issues/1745](https://github.com/Maatwebsite/Laravel-Excel/issues/1745)
