### ISSUE TITLE
No support in Laravel Lumen

### ISSUE THREAD

**Issue by jogeocc** [Jimmy-JS/laravel-report-generator#32]
el archivo "ServiceProvider.php" esta dando problemas al momento de usar la biblioteca en laravel lumen, es posible que le puedas dar soporte para que funcione en dicho framework??

Por el momento pude solucionar el error con el siguiente linea de codigo 

 public function boot()
    {
        $this->loadViewsFrom(__DIR__ . '/views', 'report-generator-view');

        if (! $this->isLumen()) {
            $this->publishes([
                __DIR__.'/../config/report-generator.php' => config_path('report-generator.php')
            ], 'laravel-report:config');
        }
        

        $this->publishes([
            __DIR__.'/views' => resource_path('views/vendor/jimmyjs'),
        ], 'laravel-report:view-template');
    }

**Comment by Jimmy-JS** [comment]
@jogeocc which lumen version are you using? and are you used the latest version of this package? (v. 1.0.24)

**Comment by Jimmy-JS** [comment]
@jogeocc this has been added on version 1.0.27.
