### ISSUE TITLE
Cannot show the page number at the bottom

### ISSUE THREAD

**Issue by tongisulaiman** [Jimmy-JS/laravel-report-generator#33]
The report is shown but the page numbers is not shown at the bottom of the report,
is there anything am doing wrong. thanks

**Comment by Jimmy-JS** [comment]
Can you tell me more detail? Are you generating excel / pdf. if it's pdf, what version of wkhtmltopdf that you use?

**Comment by Jimmy-JS** [comment]
will close this since no more comments
