### ISSUE TITLE
Need create a variation to Laravel 5.1

### ISSUE THREAD

**Issue by josejlpp** [Jimmy-JS/laravel-report-generator#35]
The helper resource_path was added in the project, but it don't exists in laravel 5.1.
I need a branch specific to Laravel 5.1, with de alteration in ServiceProvider.php line 52

**from** 
`__DIR__.'/views' => resource_path('views/vendor/laravel-report-generator')`

**to** 
`__DIR__.'/views' => base_path('resources/views/vendor/laravel-report-generator')`

**Comment by Jimmy-JS** [comment]
@josejlpp thank you for your suggestion. and sorry for make you waiting. this has been added to the latest version
