### ISSUE TITLE
Trying to make it work but report won't show any fields

### ISSUE THREAD

**Issue by JuNex03** [Jimmy-JS/laravel-report-generator#37]
Hi, I'm trying to make this work via an addon with PyroCMS. I almost copied the example code word per word, expect for the query where instead of using the model, I used "DB::Table.

The query does hold values from the database but it does not display on the PDF
![image](https://user-images.githubusercontent.com/45313034/48969209-88462a00-f036-11e8-912e-7831fc2cc3fa.png)

Here's what I''m getting:

![image](https://user-images.githubusercontent.com/45313034/48969222-ccd1c580-f036-11e8-93b3-33e55e7c61b3.png)

Here's the code:

public function displayReport(Request $request)
    {
        $fromDate = '2018-11-23';
        $toDate = '2018-11-25';
        $sortBy ='name';

        $title = 'Account Balance Report'; // Report title

        $meta = [ // For displaying filters description on header
            'Registered on' => $fromDate . ' To ' . $toDate,
            'Sort By' => $sortBy
        ];

        $queryBuilder = DB::table('testreport_accountinfo_translations')->select('name', 'created_at as registered_at', 'balance')->wherebetween('created_at', [$fromDate, $toDate])->orderBy($sortBy)->get(); 
        dd($queryBuilder);
        $columns = [ // Set Column to be displayed
            'Name' => 'name',
            'Registered At' => 'registered_at',
            'Total Balance' => 'balance',
        ];
        
        // Generate Report with flexibility to manipulate column class even manipulate column value (using Carbon, etc).
        return PDFReport::of($title, $meta, $queryBuilder, $columns)
            ->setpaper('legal')
            ->setorientation('landscape')
            ->editColumn('Registered At', [ // Change column class or manipulate its data for displaying to report
                'displayAs' => function($result) {
                    return $result->registered_at->format('d M Y');
                },
                'class' => 'left'
            ])
            ->editColumns(['Total Balance', 'Status'], [ // Mass edit column
                'class' => 'right bold'
            ])
            ->showTotal([ // Used to sum all value on specified column on the last table (except using groupBy method). 'point' is a type for displaying total with a thousand separator
                'Total Balance' => 'point' // if you want to show dollar sign ($) then use 'Total Balance' => '$'
            ])
            ->stream(); // or download('filename here..') to download pdf
    }

**Comment by Jimmy-JS** [comment]
Hi, I think the problem is your query is already return a collection but this package is just need the query builder instead of collection. you should not use get() method since it will run the query builder and return in collection.

Change your queryBuilder to:
`$queryBuilder = DB::table('testreport_accountinfo_translations')->select('name', 'created_at as registered_at', 'balance')->wherebetween('created_at', [$fromDate, $toDate])->orderBy($sortBy);`

**Comment by JuNex03** [comment]
Holy.... that fixed it! I thought the query needed to run before passing it to the pdf generator.
