### ISSUE TITLE
Date Printed on PDF only prints UTC time stamp

### ISSUE THREAD

**Issue by heidilux** [Jimmy-JS/laravel-report-generator#39]
I didn't see any way to pass in the timezone to the `<script>` section of the `general-pdf-template` blade view. I tried a few things, but was unsuccessful.

In the end, I wound up forking the repo and just removed that line altogether.

Would be nice if we could get a `setTimeZone()` method on the `ReportGenerator` class.

**Comment by Jimmy-JS** [comment]
What if you just use `date_default_timezone_set('Pacific/Nauru');` before? It should be change the timezone

**Comment by heidilux** [comment]
Sure, that would be possible, but I've already got timezones worked out everywhere else. In this case, I guess that would require setting the default, running the report, and setting the timezone back. Not the end of the world, but not ideal.

No biggie. Like I said, just forked and altered to suit my needs, but might be nice down the road ;)

Cheers!
