### ISSUE TITLE
Facades Not Working

### ISSUE THREAD

**Issue by ferdyantorand** [Jimmy-JS/laravel-report-generator#4]
Can you please tell us how to use the Facades?
I always get the Error for Non-static methods should not be called from a static context

**Comment by Jimmy-JS** [comment]
Just use it normally -> \PDFReport:of(...). If that still not work, try add this on config/app.php aliases variables

> 'PdfReport' => Jimmyjs\ReportGenerator\Facades\PdfReportFacade::class,
> 'ExcelReport' => Jimmyjs\ReportGenerator\Facades\ExcelReportFacade::class,
> 'CSVReport' => Jimmyjs\ReportGenerator\Facades\CSVReportFacade::class,
