### ISSUE TITLE
how to align total columns

### ISSUE THREAD

**Issue by imamhsn195** [Jimmy-JS/laravel-report-generator#41]

**Comment by imamhsn195** [comment]
I can align columns with class right or left calling editColumn function individually . But Can I align multiple column in a single function editColumn?
` ->editColumn('Discount', [ // Change column class or manipulate its data for displaying to report
                'class' => 'right'
            ])
            ->editColumn('Tax', [ // Change column class or manipulate its data for displaying to report
                'class' => 'right'
            ])
            ->editColumn('Total', [ // Change column class or manipulate its data for displaying to report
                'class' => 'right'
            ])`
like this

**Comment by Jimmy-JS** [comment]
@imamhsn195 yeah you can use `editColumns()` method:
`->editColumns(['Discount', 'Tax', 'Total'], ['class' => 'right']);`

**Comment by imamhsn195** [comment]
Thanks
