### ISSUE TITLE
Call to a member function when() on array

### ISSUE THREAD

**Issue by mardianad** [Jimmy-JS/laravel-report-generator#43]
why always show this error?

**Comment by Jimmy-JS** [comment]
please give your code

**Comment by christer77** [comment]
> why always show this error?



> please give your code

Hello!

**Comment by christer77** [comment]
i've a same problem "Call to a member function when() on array". Can you help me please.
This my code

**$title = 'Agence Report'; // Report title

    $meta = [ // For displaying filters description on header
        'Print date' =>  date('d-m-Y')
    ];

    $queryBuilder = DB::select('SELECT CodeAgence, DescriptionAgence FROM t_agence');

    $columns = [ 
        'CodeAgence' => 'CodeAgence',
        'DescriptionAgence' => 'DescriptionAgence'
    ];

    return PdfReport::of($title, $meta, $queryBuilder, $columns)
    ->limit(20)
    ->stream();**

**Comment by Jimmy-JS** [comment]
Thanks for the code, it looks like it's because you're using `DB::select()` instead of querying using eloquent. This package is only accepting eloquent query builder not an actual array

Please use eloquent to query your data for example: `User::select(['name'])`. Because `DB::select()` will returning an `array` while `User::select(['name'])` will return `Illuminate\Database\Eloquent\Builder`

**Comment by christer77** [comment]
Tank dear!
I try it

Le dim. 3 oct. 2021 à 12:24, Jimmy Setiawan ***@***.***> a
écrit :

**Comment by christer77** [comment]
> Thanks for the code, it looks like it's because you're using `DB::select()` instead of querying using eloquent. This package is only accepting eloquent query builder not an actual array
> 
> Please use eloquent to query your data for example: `User::select(['name'])`. Because `DB::select()` will returning an `array` while `User::select(['name'])` will return `Illuminate\Database\Eloquent\Builder`

Thanks for this dear solution.
But a new problem arises "Target class [snappy.pdf.wrapper] does not exist."

**Comment by Jimmy-JS** [comment]
You can choose whether you want to use snappy pdf or dompdf library to download / stream the pdf. 

The default pdf that is being used is snappy pdf and if you want to use snappy you need to install the library & htmltopdf. but if you want to use dompdf, then you can install dompdf package & change 'pdfLibrary' to 'dompdf' in the config. it's in the readme

<img width="885" alt="2021-10-03 at 23 22 43@2x" src="https://user-images.githubusercontent.com/9798426/135762785-09b849d3-4614-4898-a7ed-547ec2d9ab79.png">
