### ISSUE TITLE
Report generator for  Laravel-nova

### ISSUE THREAD

**Issue by kenkaigu** [Jimmy-JS/laravel-report-generator#46]
is there a laravel nova package for this awesome plugin?

**Comment by Jimmy-JS** [comment]
Whoops unfortunately this package is not on laravel nova. And I don't think I have time for that :( but anyone is free to tweak it for laravel nova for sure. thanks!

**Comment by SalekurPolas** [comment]
> is there a laravel nova package for this awesome plugin?

You can try this,
https://github.com/SalekurPolas/nova-report-generator

**Comment by kenkaigu** [comment]
> > is there a laravel nova package for this awesome plugin?
> 
> You can try this, https://github.com/SalekurPolas/nova-report-generator

Thank you so much ... Can it also do the data manupulation ( the additions and all that stuff )
