### ISSUE TITLE
laravel 5.8 compatibility?

### ISSUE THREAD

**Issue by mpixelz** [Jimmy-JS/laravel-report-generator#47]
Hi,
is there any chance to have laravel 5.8 compatibility? im unable to install on 5.8

**Comment by mpixelz** [comment]
any help? :(

**Comment by mpixelz** [comment]
any help?
@Jimmy-JS

**Comment by Jimmy-JS** [comment]
Now it support laravel 7.0 as well. just pull version 2.0 thanks for waiting!
