### ISSUE TITLE
Laravel ^6.0 compatability?

### ISSUE THREAD

**Issue by RhysLees** [Jimmy-JS/laravel-report-generator#49]

**Comment by bilalch193** [comment]
I managed to make it work on Laravel 6.

1. First download the zip file of package.
2. Create a folder in your project's root folder i.e local_packages
3. Now unzip the this package in this folder. Structure could be like
your_project/local_packages/jimmyjs/laravel-report-generator/src
4. edit composer.json of report generator and replace version of maatwebsite as
"maatwebsite/excel": "^3.0"
5. Now open yours project's composer.json file and add this in require block
"jimmyjs/laravel-report-generator": "@dev",
6. Also add following code in this composer.json
    "repositories": [
        {
            "type": "path",
            "url": "local_packages/jimmyjs/laravel-report-generator"
        }
    ],

> Note: Match your folder structure accordingly
7. Open local_packages/jimmyjs/laravel-report-generator/src/ServiceProvider.php and add
use Illuminate\Support\Str;
and in isLumen() function, replace str_contains with Str::contains

8. Open local_packages/jimmyjs/laravel-report-generator/src/ReportGenerator.php and add at top
use Illuminate\Support\Str;
and in mapColumns() function, replace snake_case with
Str::snake
9. Now before using package, make sure you installed wkhtmltopdf and also snappy.

So far I have tried first example and it is working fine for me using above fix.

**Comment by Jimmy-JS** [comment]
Now it support laravel 7.0 as well. just pull version 2.0 thanks for waiting!
