### ISSUE TITLE
Error: Illegal offset type

### ISSUE THREAD

**Issue by wagnerdracha** [Jimmy-JS/laravel-report-generator#5]
Hi 

Laravel return this error: Illegal offset type

This is my page:

`...

        $fromDate = $request->input('rm_dt_inicio');
        $toDate   = $request->input('rm_dt_fim');

        // Report title
        $title = 'Relatório de Monitoramento';

        // For displaying filters description on header
        $meta = [
            'Registrados em' => $fromDate . ' To ' . $toDate
        ];

        // Do some querying..
        $queryBuilder = \App\Entidade::get();

        // Set Column to be displayed
        $columns = [
            'Nome' => 'ent_nome',
            'Nome do Display' => 'ent_nome',
            'Data de Cadastro' => 'ent_nome'
        ];

        return PdfReport::of($title, $meta, $queryBuilder, $columns)
            ->editColumn(['Nome', 'Nome do Display', 'Data de Cadastro'], [
                'class' => 'right bold'
            ])
            ->setPaper('a4')
            ->limit(20)
            ->download('teste.pdf');

...`

**Comment by Jimmy-JS** [comment]
@wagnerdracha Can you provide laravel stack error log for further inspection?

**Comment by Jimmy-JS** [comment]
I'll close this since there is no further information
