### ISSUE TITLE
facing issue `Method Illuminate\Database\Eloquent\Collection::cursor does not exist` while creating and downloading PdfReport

### ISSUE THREAD

**Issue by iabduul7** [Jimmy-JS/laravel-report-generator#55]
**Method Illuminate\Database\Eloquent\Collection::cursor does not exist. (View: ~demo_project\vendor\jimmyjs\laravel-report-generator\src\views\general-pdf-template.blade.php)**

![image](https://user-images.githubusercontent.com/24309704/85016165-9c0a3180-b182-11ea-9b7b-ed328e4f4085.png)

how do resolve this??

**Comment by aimalamiri** [comment]
Hello, @iabduul7  did you find a solution for this?

**Comment by iabduul7** [comment]
> Hello, @iabduul7 did you find a solution for this?

nope I didn't, I quite using it...

**Comment by iabduul7** [comment]
I used simple solution to generate reports.
created a `table` with a column -`report`- of `json type` then just for whomever I wanted to create report, I stored records in `json format` and then on frontend I showed that `json result` with `HTML table`

**Comment by amaurycid** [comment]
This should happen when terminating your queryBuilder with get(), or all(), etc., passing a Collection instead of a Eloquent query object.
