### ISSUE TITLE
I Added an option to save file to disk, check the code on the description

### ISSUE THREAD

**Issue by xtreme2020** [Jimmy-JS/laravel-report-generator#56]
Hi,
I add the option to export file to disk using the following code, the following example was created on the ExcelReport Class
this also can support custom disk.

  public function storeFile($filename,$location=null,$customDisk=null){
        $path=$location !=null ? $localtion."/": "";
        $export = $this->make();
        return Excel::store($export,$path."{$filename}.{$this->format}",$customDisk);
    }
i hope you can added it .

**Comment by alsahlawi** [comment]
thanks @xtreme2020 , I have used this one and it works like charm!

**Comment by Jimmy-JS** [comment]
Hi, thanks for your suggestion. In version 2.1.0 I add store() method to all report types.
