### ISSUE TITLE
Call to a member function cursor() on null

### ISSUE THREAD

**Issue by juanklayd** [Jimmy-JS/laravel-report-generator#57]
Hi. I added this package to my project. But when I run the program, it has this error:
Error
Call to a member function cursor() on null (View: C:\xampp\htdocs\qatest2\vendor\jimmyjs\laravel-report-generator\src\views\general-pdf-template.blade.php)

here's the code to my controller:

`public function filterReport(Request $request)
    {
        $school = $request->select1;
        $accredStatus = $request->accredStatus;

         $title = 'Accreditation Report';
        $meta = [ 
                'School' => $school,
                'Sort By' => $accredStatus
            ];

         $queryBuilder = DB::table('prgrm_accreds')
                        ->join('acad_prgrms', 'acad_prgrms.id', 'prgrm_accreds.acad_prgrm_id')
                        ->join('schools', 'schools.id', 'acad_prgrms.school_id')
                        ->where('schools.school_name', $school)
                        ->where('accred_stats.accred_status', $accredStatus)
                        ->where('current', 'yes')
                        ->get();

         return PdfReport::of($title, $meta, $queryBuilder, $columns)
                    ->limit(20) 
                    ->stream();

    }`

**Comment by searsandrew** [comment]
I don't know if you solved this, but I can across the same issue.
The problem is the ->get() at the end of your $queryBuilder, its unnecessary in this usage.
