### ISSUE TITLE
Overall Architecture

### ISSUE THREAD

**Issue by mokhosh** [Jimmy-JS/laravel-report-generator#59]
Thanks for the great package. I really like the functionality, but I have some major issues with the design.
I'll explain the situation and please let me know if I'm missing something.

Let's say I want to create a `ReportService` that takes a query and generates a PDF or Excel file. Ideally it should look like this:
```php
$query = User::query();

return (new ReportService)->exportPdf($query);
```
And `exportPdf` would have a signature like this:
```php
public function exportPfd(Builder $query, array $columns = [], string $title = 'Report', array $meta = [])
```
Getting all the columns if no columns are passed, and using defaults for title and meta as well.

This method must not be concerned with our application models and how we store and access data. It would be even better if it just received a collection instead of an Eloquent `Builder` to be more generic. These are not addressed in the readme example but can be done in our code. BUT, where there is a tight coupling that you can't easily break, is how you use `editColumn` to modify data.

I think we can use model's `toArray` for example to decouple this piece.

Shooting from the hip here, so let me know what you think.

**Comment by Jimmy-JS** [comment]
Hey mokhosh, thanks for your feedback. I'm sorry for the very slow response. I haven't touch laravel for a long time now.

based on your feedback, I don't think we can change eloquent builder to collection since it helps generating report with big data using chunk() / cursor() to avoid memory limit. but any PR is welcomed :))
