### ISSUE TITLE
Remove No column

### ISSUE THREAD

**Issue by shivampaw** [Jimmy-JS/laravel-report-generator#6]
Is there any way to remove the No column that is auto added?

**Comment by shivampaw** [comment]
Had to hide it with CSS

```
->setCss([
                'table tr td:first-child' => 'display: none',
                'table tr th:first-child' => 'display: none'
            ])
```

**Comment by bgarrison25** [comment]
I came to the issues section for the same reason. First I wanted to see if there was a setting to remove it. There isn't. Then I wanted to see if there was a setting so I could set my own view so that I could just copy and paste the view they are using and remove the "NO" column. Nope. Either of these options would be useful (or both). Would you like me to put in a pull request for them? (shouldn't be a difficult task)

**Comment by bgarrison25** [comment]
#7 added to set an option to remove the no column. Still think another PR would be nice to allow for a custom view

**Comment by shivampaw** [comment]
If you wanted a custom view you’d just use DomPDF by itself to be honest.

**Comment by bgarrison25** [comment]
this is a wrapper around that....it'd be nice to create a custom view so you can use the other options but yeah i get your point.

**Comment by bgarrison25** [comment]
I'm more concerned with the fact that this has been in here for a week WITH a pull request and nobody has answered.....I may just start using my fork.

**Comment by mailnike** [comment]
@shivampaw css also removed date range / sort by fields below top header. How do I get them back? @bgarrison25 waiting for your merge by repo owner. It looks good though.

**Comment by shivampaw** [comment]
@mailnike Try:

    ->setCss([
        'table tr td.left:first-child' => 'display: none',
        'table tr th.left:first-child' => 'display: none'
    ])

I haven't tested it but it should work.

**Comment by rajitha-bandara** [comment]
Below code is not working for me while trying to hide No column,
```
->setCss([
    'table tr td.left:first-child' => 'display: none',
    'table tr th.left:first-child' => 'display: none'
])
```

**Comment by shivampaw** [comment]
@rajitha-bandara what error

**Comment by rajitha-bandara** [comment]
@shivampaw No visible error. But it is still showing the No column. In excel reports, I think this column is redundant in most cases. Anyway thanks for this smart lib.
