### ISSUE TITLE
Target class [snappy.pdf.wrapper] does not exist.

### ISSUE THREAD

**Issue by pravnkay** [Jimmy-JS/laravel-report-generator#64]
I am already using laravel-dompdf for invoice generation.
But, when I use this package to generate a report. this is all I get.

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [snappy.pdf.wrapper] does not exist.
```

The code I use for a dummy report generation is,

    public function displayReport()
	{

	  $title = 'Registered User Report'; 

	  $meta = [
	  ];

	  $queryBuilder = User::select(['name']);

	  $columns = [ 
		'Name' => 'name',
	  ];

	  return PdfReport::of($title, $meta, $queryBuilder, $columns)
		->limit(20) 
		->stream(); 
	}

In the package source code file, PdfReport.php

```
try {
  $pdf = \App::make('snappy.pdf.wrapper');
  $pdf->setOption('footer-font-size', 10);
  $pdf->setOption('footer-left', 'Page [page] of [topage]');
  $pdf->setOption('footer-right', 'Date Printed: ' . date('d M Y H:i:s'));
} catch (\ReflectionException $e) {
  try {
    $pdf = \App::make('dompdf.wrapper');
  } catch (\ReflectionException $e) {
    throw new \Exception('Please install either barryvdh/laravel-snappy or laravel-dompdf to generate PDF Report!');
  }
}
```

If I change interchange the detection of snappy and dompdf wrappers like this,

```
try {
   $pdf = \App::make('dompdf.wrapper');
} catch (\ReflectionException $e) {
  try {
    $pdf = \App::make('snappy.pdf.wrapper');
    $pdf->setOption('footer-font-size', 10);
    $pdf->setOption('footer-left', 'Page [page] of [topage]');
    $pdf->setOption('footer-right', 'Date Printed: ' . date('d M Y H:i:s'));
  } catch (\ReflectionException $e) {
    throw new \Exception('Please install either barryvdh/laravel-snappy or laravel-dompdf to generate PDF Report!');
  }
}
```
it works perfectly.

Any help on this is much appreciated. Thanks.

**Comment by ershadow786** [comment]
Did you solve this? Changing code in vendor directory is not good idea.

**Comment by Jimmy-JS** [comment]
Hello, sorry for slow response. I've added a config to choose which pdf package will be used for generating pdf in version 2.0.1. you need to publish the config first. for more info, read in the readme
