### ISSUE TITLE
Call to undefined function thousandSeparator()

### ISSUE THREAD

**Issue by djipang** [Jimmy-JS/laravel-report-generator#67]
Hello
i got some error while using thousandSeparator function

here is my code for column manipulation

```
->editColumns(['Nominal'], [ // Mass edit column
                    'class' => 'right bold',
                    'displayAs' => function($result) {
                        return thousandSeparator($result->jumlah);
                    }
                ])
```
![thousand separator](https://user-images.githubusercontent.com/61958567/121629259-fe032b80-caa4-11eb-97a1-5d5ba3e57701.jpg)

**Comment by Jimmy-JS** [comment]
you need to define that function manually or just use the 'point' type
