### ISSUE TITLE
Call to undefined method Symfony\\Component\\HttpFoundation\\StreamedResponse::header()?

### ISSUE THREAD

**Issue by ershadow786** [Jimmy-JS/laravel-report-generator#68]
Hola all,

I have installed lib using composer and using  laravel-dompdf.

First issue that i am facing is that when i use this package i get 

> Illuminate\Contracts\Container\BindingResolutionException
Target class [snappy.pdf.wrapper] does not exist.

but default it's taking snappy for report generation but  when i install 
snappy using 
> composer require barryvdh/laravel-snappy
i get error as below :

 > Call to undefined method Symfony\\Component\\HttpFoundation\\StreamedResponse::header()?

Any help is appreciated for this .

Sample code :  
 
```
public function displayReport()
{

  $title = 'Registered User Report'; 

  $meta = [
  ];

  $queryBuilder = User::select(['name']);

  $columns = [ 
	'Name' => 'name',
       'Registered On' => function($queryBuilder){
                return $queryBuilder->created_at;
            }
  ];

  return PdfReport::of($title, $meta, $queryBuilder, $columns)
	->limit(20) 
	->stream(); 
}

```

**Comment by Jimmy-JS** [comment]
It working fine in mine. have you install wkhtmltopdf?

**Comment by Jimmy-JS** [comment]
and make sure you're installing the correct wkhtmltopdf that match your device architecture
