### ISSUE TITLE
Compatibility with Maatwebsite excel 3.0

### ISSUE THREAD

**Issue by tszaniszlo** [Jimmy-JS/laravel-report-generator#9]
Hi, I would like to use Maatwebsite Excel 3.0 and report generator but report generator requires 2.1.* and I am not able to use thge package. Will this be compatible with Excel 3.0?

**Comment by NormanEdance** [comment]
@tszaniszlo Maatwebsite Excel 3.0 is not ready yet. It's not even adding any style from the views  :(

**Comment by Jimmy-JS** [comment]
I don't have time for now to update excel using Maatwebsite excel 3.0. Maybe will add this feature later :D

**Comment by mpixelz** [comment]
version 3.1 is out.. any chance of compatibility?

**Comment by mailnike** [comment]
any update on this :(

**Comment by esquinas** [comment]
Maatwebsite/excel 2.1.10 is not compatible with Laravel ^5.5
I tried installing this report-generator on Laravel 5.6 without success.
Also, Yajra/laravel-datatables-buttons requires Maatwebsite/excel ^3 making it incompatible with this report generator.

**Comment by coolsam726** [comment]
@Jimmy-JS any updates please ? I am using Laravel 5.7 and most of the features I am using require excel ^3.1, hence I cannot even install the report generator

**Comment by Jimmy-JS** [comment]
v2.0.0 has released. please do update. at this version, it uses maatwebsite/excel v3.1
